name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build -t jvefferson/nginx:${{ github.sha }} .

      - name: List Images
        run: docker images